# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: TerraformValidate
    jobs:
    - job: terrafformValidateJob
      continueOnError: false
      steps:
         - task: PublishPipelineArtifact@1
           displayName: Publish Artifacts
           inputs:
             targetPath: '$(System.DefaultWorkingDirectory)/manifest'
             publishLocation: 'pipeline'
         - task: TerraformTaskV4@4
           inputs:
             provider: 'azurerm'
             command: 'init'
             workingDirectory: '$(System.DefaultWorkingDirectory)/manifest'
             backendAzureRmUseEntraIdForAuthentication: true
             backendServiceArm: 'terraform-aks-azurerm-svc-con'
             backendAzureRmResourceGroupName: 'terraform-storage-rg'
             backendAzureRmStorageAccountName: 'terraformtfstate1844'
             backendAzureRmContainerName: 'tfstatefiles'
             backendAzureRmKey: 'aks-base.tfstate'
        
         
         